[build]
  base    = "frontend/eportal"
  command = "npm run build"
  publish = "frontend/eportal/dist"

[build.environment]
  VITE_API_URL = "https://devlogics-backend-5ho1.vercel.app/api"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
